### ISSUE TITLE
Question re: The PCB needs a redesign due to design flaws!

### ISSUE THREAD

**Issue by philippsandi** [XasWorks/LZRTag#79]
Hey there, 
very nice project :-) 
I stumbled upon this caution above regarding the PCB and wanted to ask, if you could specify the existing design flaws?

Thanks and greetings,
Philipp

**Comment by Xasin** [comment]
Ah, that might be because I still need to update the Aisler website!
I actually got through most of the redesign and tested a Revision 2 of the PCB, but due to my University getting busier I was so far unable to properly update things there.

The PCB is pretty much fully done, but if you are patient, I would like to give it a quick review in the next day or two to make sure I didn't forget anything :)

**Comment by philippsandi** [comment]
Oh cool, thank you for the quick answer - I'm in no hurry, so I'll gladly wait for the Revision 2. :-)

**Comment by Xasin** [comment]
No problem @philippsandi, it's always a pleasure to see people enjoying my work! 

I went over the PCB files, and I think I was able to round everything off already, so I think it's safe to use the current design files. The main problems were with a button that... I no longer have anyways <.<'

I recommend ordering the boards off of Aisler or JLCPCB, depending on how many you need.
Usually I'd say Aisler is OK, but right now their BOM cost is REALLY messed up - it's telling me 2000€ for one set of electronics for my Lasertag system, which used to be 30€...

I have a Digikey parts list I can give you though:
https://hackaday.io/project/160804-lzrtag-flexible-diy-lasertag/files

Will this be sufficient?

**Comment by philippsandi** [comment]
Awesome - thank you very much for checking! 🙂 

Oh okay, yeah that seems a little expensive 😄 I've never tried Aisler before, but maybe I'll give it a shot, as the prices are IMO appropriate for production in germany. 

Great, the parts list is very helpful aswell 👍 

So thanks again, I'll order everything necessary and then wait for some free time to assemble :-)

**Comment by Xasin** [comment]
Looking forward to it!
There's been a group in south Germany that quite successfully assembled... I think 13 boards in total?
And it all seemed to work quite well for them ^^

**Comment by philippsandi** [comment]
Oh wow, that's nice - awesome! 👍 

I'm sorry to bother you again - I just downloaded the KiCad files from github and saw that it's PCB Rev. V3.0, but the uploaded gerber files on the Aisler page are Rev. V3.2. Could you upload the files for V3.2 to github aswell? :-)

Thanks again for your time!

**Comment by Xasin** [comment]
Yeah sure - I think they're in the dev_3.2 branch (I just checked and ran the DRC there, it's clean), and I just never got around to properly merging the changes in.
The files on HackADay should be recent too.

One small request: 
Run the DRC checker if you're going to be using the KiCAD files. I do have all my git changes pushed, so you should be good to go, and I think it should be OK - but I don't know if maybe the footprint libraries on your end look different.
